language: node_js
node_js:
  - 14
services:
  - postgresql
before_script:
  - psql -c 'create database "ledger-test";' -U postgres
  - psql -c "CREATE USER pguser WITH PASSWORD 'pgpass';" -U postgres
  - psql -d "ledger-test" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U postgres
