language: node_js
node_js:
  - 14
services:
  - postgresql
before_script:
  - psql -c 'create database "expenses-test";' -U postgres
  - psql -c "CREATE USER pguser WITH PASSWORD 'pgpass';" -U postgres
